config/routes.rb
Rails.application.routes.draw do
  resources :expertise_professors
  resources :expertises
  resources :professors

  root to: "professors#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expertise.rb
class Expertise < ApplicationRecord
	has_many :expertise_professors
	has_many :professors, through: :expertise_professors
end

app/models/expertise_professor.rb
class ExpertiseProfessor < ApplicationRecord
  belongs_to :expertise
  belongs_to :professor
end

app/models/professor.rb
class Professor < ApplicationRecord
	has_many :expertise_professors, dependent: :destroy
	has_many :expertises, through: :expertise_professors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/expertise_professors_controller.rb
class ExpertiseProfessorsController < ApplicationController
  before_action :set_expertise_professor, only: [:show, :edit, :update, :destroy]

  # GET /expertise_professors
  # GET /expertise_professors.json
  def index
    @expertise_professors = ExpertiseProfessor.all
  end

  # GET /expertise_professors/1
  # GET /expertise_professors/1.json
  def show
  end

  # GET /expertise_professors/new
  def new
    @expertise_professor = ExpertiseProfessor.new
  end

  # GET /expertise_professors/1/edit
  def edit
  end

  # POST /expertise_professors
  # POST /expertise_professors.json
  def create
    @expertise_professor = ExpertiseProfessor.new(expertise_professor_params)

    respond_to do |format|
      if @expertise_professor.save
        format.html { redirect_to @expertise_professor, notice: 'Expertise professor was successfully created.' }
        format.json { render :show, status: :created, location: @expertise_professor }
      else
        format.html { render :new }
        format.json { render json: @expertise_professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expertise_professors/1
  # PATCH/PUT /expertise_professors/1.json
  def update
    respond_to do |format|
      if @expertise_professor.update(expertise_professor_params)
        format.html { redirect_to @expertise_professor, notice: 'Expertise professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @expertise_professor }
      else
        format.html { render :edit }
        format.json { render json: @expertise_professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expertise_professors/1
  # DELETE /expertise_professors/1.json
  def destroy
    @expertise_professor.destroy
    respond_to do |format|
      format.html { redirect_to expertise_professors_url, notice: 'Expertise professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expertise_professor
      @expertise_professor = ExpertiseProfessor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expertise_professor_params
      params.require(:expertise_professor).permit(:expertise_id, :professor_id, :name)
    end
end

app/controllers/expertises_controller.rb
class ExpertisesController < ApplicationController
  before_action :set_expertise, only: [:show, :edit, :update, :destroy]

  # GET /expertises
  # GET /expertises.json
  def index
    @expertises = Expertise.all
  end

  # GET /expertises/1
  # GET /expertises/1.json
  def show
  end

  # GET /expertises/new
  def new
    @expertise = Expertise.new
  end

  # GET /expertises/1/edit
  def edit
  end

  # POST /expertises
  # POST /expertises.json
  def create
    @expertise = Expertise.new(expertise_params)

    respond_to do |format|
      if @expertise.save
        format.html { redirect_to @expertise, notice: 'Expertise was successfully created.' }
        format.json { render :show, status: :created, location: @expertise }
      else
        format.html { render :new }
        format.json { render json: @expertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expertises/1
  # PATCH/PUT /expertises/1.json
  def update
    respond_to do |format|
      if @expertise.update(expertise_params)
        format.html { redirect_to @expertise, notice: 'Expertise was successfully updated.' }
        format.json { render :show, status: :ok, location: @expertise }
      else
        format.html { render :edit }
        format.json { render json: @expertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expertises/1
  # DELETE /expertises/1.json
  def destroy
    @expertise.destroy
    respond_to do |format|
      format.html { redirect_to expertises_url, notice: 'Expertise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expertise
      @expertise = Expertise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expertise_params
      params.require(:expertise).permit(:name)
    end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  # GET /professors
  # GET /professors.json
  def index
    @search = Professor.search(params[:q])
    @professors = @search.result(distinct: true)
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params      
      params.require(:professor).permit(:name, expertise_ids:[])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expertise_professors_helper.rb
module ExpertiseProfessorsHelper
end

app/helpers/expertises_helper.rb
module ExpertisesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/expertise_professors/_form.html.erb
<%= form_with(model: expertise_professor, local: true) do |form| %>
  <% if expertise_professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expertise_professor.errors.count, "error") %> prohibited this expertise_professor from being saved:</h2>

      <ul>
      <% expertise_professor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :expertise_id %>
    <%= form.text_field :expertise_id, id: :expertise_professor_expertise_id %>
  </div>

  <div class="field">
    <%= form.label :professor_id %>
    <%= form.text_field :professor_id, id: :expertise_professor_professor_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :expertise_professor_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/expertise_professors/edit.html.erb
<h1>Editing Expertise Professor</h1>

<%= render 'form', expertise_professor: @expertise_professor %>

<%= link_to 'Show', @expertise_professor %> |
<%= link_to 'Back', expertise_professors_path %>

app/views/expertise_professors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expertise Professors</h1>

<table>
  <thead>
    <tr>
      <th>Expertise</th>
      <th>Professor</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expertise_professors.each do |expertise_professor| %>
      <tr>
        <td><%= expertise_professor.expertise %></td>
        <td><%= expertise_professor.professor %></td>
        <td><%= expertise_professor.name %></td>
        <td><%= link_to 'Show', expertise_professor %></td>
        <td><%= link_to 'Edit', edit_expertise_professor_path(expertise_professor) %></td>
        <td><%= link_to 'Destroy', expertise_professor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expertise Professor', new_expertise_professor_path %>

app/views/expertise_professors/new.html.erb
<h1>New Expertise Professor</h1>

<%= render 'form', expertise_professor: @expertise_professor %>

<%= link_to 'Back', expertise_professors_path %>

app/views/expertise_professors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Expertise:</strong>
  <%= @expertise_professor.expertise %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @expertise_professor.professor %>
</p>

<p>
  <strong>Name:</strong>
  <%= @expertise_professor.name %>
</p>

<%= link_to 'Edit', edit_expertise_professor_path(@expertise_professor) %> |
<%= link_to 'Back', expertise_professors_path %>

app/views/expertises/_form.html.erb
<%= form_with(model: expertise, local: true) do |form| %>
  <% if expertise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expertise.errors.count, "error") %> prohibited this expertise from being saved:</h2>

      <ul>
      <% expertise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :expertise_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/expertises/edit.html.erb
<h1>Editing Expertise</h1>

<%= render 'form', expertise: @expertise %>

<%= link_to 'Show', @expertise %> |
<%= link_to 'Back', expertises_path %>

app/views/expertises/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expertises</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expertises.each do |expertise| %>
      <tr>
        <td><%= expertise.name %></td>
        <td><%= link_to 'Show', expertise %></td>
        <td><%= link_to 'Edit', edit_expertise_path(expertise) %></td>
        <td><%= link_to 'Destroy', expertise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expertise', new_expertise_path %>

app/views/expertises/new.html.erb
<h1>New Expertise</h1>

<%= render 'form', expertise: @expertise %>

<%= link_to 'Back', expertises_path %>

app/views/expertises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @expertise.name %>
</p>

<%= link_to 'Edit', edit_expertise_path(@expertise) %> |
<%= link_to 'Back', expertises_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheckoutHasManyThrough</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/professors/_form.html.erb
<%= form_with(model: professor, local: true) do |form| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% professor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :professor_name %>
  </div>

  <div class="field">
    <%= form.label "Area of Expertise" %><br />
    <%= form.collection_check_boxes :expertise_ids, Expertise.all, :id, :name do |b| %>
      <div class="collection-check-box">
        <%= b.check_box %>
        <%= b.label %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<p id="notice"><%= notice %></p>

<fieldset class="search-field">
  <legend>Search Our Database</legend>
  <%= search_form_for @search do |f| %>
    <div class="field">
      <%= f.label :name_cont, "Name contains" %>
      <%= f.text_field :name_cont %>
    </div>

    <div class="field">
      <%= f.label "Area of Expertise" %><br />
      <%= f.collection_check_boxes :expertises_id_in_any, Expertise.all, :id, :name do |b| %>
        <div class="collection-check-box">
          <%= b.check_box %>
          <%= b.label %>
        </div>
      <% end %>
    </div>

    <div class="actions"><%= f.submit "Search" %></div>
  <% end %>
</fieldset>

<h1>Professors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Expertises</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professors.each do |professor| %>
      <tr>
        <td><%= professor.name %></td>
        <td><%= professor.expertises.map(&:name).sort.join(", ") %></td>
        <td><%= link_to 'Show', professor %></td>
        <td><%= link_to 'Edit', edit_professor_path(professor) %></td>
        <td><%= link_to 'Destroy', professor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 

<br>

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/new.html.erb
<h1>New Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @professor.name %>
</p>

<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professors_path %>